/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package concessionariav2;

import java.util.Date;

/**
 *
 * @author Kleber
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrame
     */
    public JFramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastrarFuncionario = new javax.swing.JButton();
        cadastrarVeiculo = new javax.swing.JButton();
        cadastrarCliente = new javax.swing.JButton();
        exibeEstoque = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastrarFuncionario.setText("Cadastrar Funcionario");
        cadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionarioActionPerformed(evt);
            }
        });

        cadastrarVeiculo.setText("Cadastrar Veiculo");
        cadastrarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarVeiculoActionPerformed(evt);
            }
        });

        cadastrarCliente.setText("Cadastrar Cliente");
        cadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarClienteActionPerformed(evt);
            }
        });

        exibeEstoque.setText("Exibir Estoque");
        exibeEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibeEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exibeEstoque)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadastrarFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrarVeiculo)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarFuncionario)
                    .addComponent(cadastrarCliente)
                    .addComponent(cadastrarVeiculo))
                .addGap(31, 31, 31)
                .addComponent(exibeEstoque)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
        JFrameCadastroFuncionario ct =  new JFrameCadastroFuncionario();
        ct.setVisible(true);
    }//GEN-LAST:event_cadastrarFuncionarioActionPerformed

    private void cadastrarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarVeiculoActionPerformed

    private void cadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarClienteActionPerformed

    private void exibeEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibeEstoqueActionPerformed
        Estoque e = new Estoque();
        
        e.listaCarros.add(new Carro(5, "cvt", true, 20, "eletrica", "Honda", "HRV", new Date(2024), new Date(2024), 3000, 97500f));
        e.listaCarros.add(new Carro(5, "manual", false, 16, "hidraulica", "Ford", "Fiesta", new Date(2022), new Date(2022), 5000, 45000f));
        e.listaCarros.add(new Carro(5, "manual", false, 15, "hidraulica", "Chevrolet", "Onix", new Date(2023), new Date(2023), 1500, 60000f));
        e.listaCarros.add(new Carro(5, "manual", true, 17, "eletrica", "Honda", "Civic", new Date(2024), new Date(2024), 3000, 97500f));
        e.listaCarros.add(new Carro(5, "automatico", true, 18, "eletrica", "Toyota", "Corolla", new Date(2023), new Date(2023), 2000, 85000f));
        e.listaCarros.add(new Carro(5, "cvt", true, 20, "eletrica", "Honda", "HRV", new Date(2024), new Date(2024), 3000, 97500f));
        e.listaCarros.add(new Carro(5, "automatico", true, 19, "eletrica", "Volkswagen", "Golf", new Date(2023), new Date(2023), 2500, 120000f));
        e.listaCarros.add(new Carro(5, "manual", false, 16, "hidraulica", "Fiat", "Uno", new Date(2023), new Date(2023), 1800, 35000f));
        e.listaCarros.add(new Carro(5, "cvt", true, 19, "eletrica", "Nissan", "Kicks", new Date(2023), new Date(2023), 2200, 80000f));
        e.listaCarros.add(new Carro(5, "automatico", true, 18, "eletrica", "Jeep", "Renegade", new Date(2024), new Date(2024), 4000, 90000f));
        e.listaCarros.add(new Carro(5, "manual", false, 17, "hidraulica", "Hyundai", "HB20", new Date(2024), new Date(2024), 3500, 60000f));
        
        System.out.println("---------------------------------------------------------------------------------");
        
        for(int i =0; i < e.listaCarros.size();i++){
            System.out.println("""
                           Descricao do veiculo:
                           Fabricante:""" + e.listaCarros.get(i).getFabricante() + 
                            "\nModelo: " +  e.listaCarros.get(i).getModelo() + 
                            "\nAno de Fabricacao: " +  e.listaCarros.get(i).getAnoFabricacao().getTime() + 
                            "\nAno do Modelo:" +  e.listaCarros.get(i).getAnoModelo().getTime() + 
                            "\nKm:" + e.listaCarros.get(i).getKm() +
                            "\nValor:" +  e.listaCarros.get(i).getValor() + 
                            "\nNumero de Portas:" +  e.listaCarros.get(i).getNumeroPortas() + 
                            "\nTipo de cambio:" +  e.listaCarros.get(i).getTipoCambio() + 
                            "\nAr condicionado:" + e.listaCarros.get(i).isArCondicionado() + 
                            "\nAro:" +  e.listaCarros.get(i).getAro() + 
                            "\nTipo de direcao:" +  e.listaCarros.get(i).getTipoDirecao() +
        
                "\n---------------------------------------------------------------------------------"
        );
        }
        
        
        
    }//GEN-LAST:event_exibeEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarCliente;
    private javax.swing.JButton cadastrarFuncionario;
    private javax.swing.JButton cadastrarVeiculo;
    private javax.swing.JButton exibeEstoque;
    // End of variables declaration//GEN-END:variables
}
